// Generated by scratchpad/gen_rift_spots.py -- do not edit by hand.
// Candidate tiles for runtime rift randomisation. Every listed spot is
// walkable, clear of NPCs/warps, and the whole set was verified with all
// spots occupied at once: every warp and map edge still reaches every
// other, so any subset the game picks can never block a route.

static const struct RiftSpot sRiftSpots_ROUTE1[] = {
    {18,  9}, {14, 29}, {14, 35}, { 5, 24}, {17, 13}, { 6, 35}, {13,  9}, { 6, 19}, {17, 24}, { 4, 30}, { 5, 14}, { 9, 30}, {13, 24}, {19,  5},
};

static const struct RiftSpot sRiftSpots_VIRIDIAN_CITY[] = {
    {18, 22}, {18, 26}, {26, 22}, {13, 20}, {17, 34}, {31, 20}, {13, 32}, {22, 35}, {36, 34}, {29,  8}, {38, 23}, {31, 26}, {39, 27}, {22,  8},
};

static const struct RiftSpot sRiftSpots_ROUTE2[] = {
    { 7,  9}, {19, 30}, {16, 17}, { 6,  5}, {18, 36},
};

static const struct RiftSpot sRiftSpots_VIRIDIAN_FOREST[] = {
    { 9, 60}, { 5, 33}, {13, 21}, {35, 60}, { 5, 17}, {37, 18}, {21, 23}, {29, 17}, {18,  9}, {42, 21}, {14,  9}, {29, 54}, {15, 29}, {14, 55},
};

static const struct RiftSpot sRiftSpots_PEWTER_CITY[] = {
    {31, 34}, {34, 20}, {25, 35}, {35,  6}, {36, 16}, {28, 22}, {11, 35}, {10, 11}, {26, 14}, {37, 35}, {16, 35}, {19, 29}, {23, 31}, {16, 11},
};

static const struct RiftSpot sRiftSpots_ROUTE3[] = {
    {37, 14}, {26,  6}, {41, 16}, {17, 11}, {43, 12}, {67, 14}, {73, 16}, {60, 15}, {70,  4}, {17,  6},
};

static const struct RiftSpot sRiftSpots_MT_MOON_1F[] = {
    { 8, 36}, {37, 11}, {23,  5}, {36, 26}, {35, 20}, {29,  8}, {37,  5}, { 7,  5}, {39, 36}, { 9, 16}, {21,  9}, { 8, 32}, {15, 20}, {32, 25},
};

static const struct RiftSpot sRiftSpots_MT_MOON_B2F[] = {
    {39, 30}, {26, 19}, {35, 22}, {11,  6}, {30, 16}, {10, 35}, {40, 17}, {39, 37}, {15,  6}, {10, 24}, {17, 11}, { 5,  6}, {11, 16}, {10, 31},
};

static const struct RiftSpot sRiftSpots_CERULEAN_CITY[] = {
    {33, 25}, {37, 17}, {23, 25}, {25, 12}, {29, 16}, {15, 23}, {11, 23}, {18, 29}, {10, 15}, {29, 25}, {19, 24},
};

static const struct RiftSpotList sRiftSpotLists[] = {
    { MAP_GROUP(MAP_ROUTE1), MAP_NUM(MAP_ROUTE1), ARRAY_COUNT(sRiftSpots_ROUTE1), sRiftSpots_ROUTE1 },
    { MAP_GROUP(MAP_VIRIDIAN_CITY), MAP_NUM(MAP_VIRIDIAN_CITY), ARRAY_COUNT(sRiftSpots_VIRIDIAN_CITY), sRiftSpots_VIRIDIAN_CITY },
    { MAP_GROUP(MAP_ROUTE2), MAP_NUM(MAP_ROUTE2), ARRAY_COUNT(sRiftSpots_ROUTE2), sRiftSpots_ROUTE2 },
    { MAP_GROUP(MAP_VIRIDIAN_FOREST), MAP_NUM(MAP_VIRIDIAN_FOREST), ARRAY_COUNT(sRiftSpots_VIRIDIAN_FOREST), sRiftSpots_VIRIDIAN_FOREST },
    { MAP_GROUP(MAP_PEWTER_CITY), MAP_NUM(MAP_PEWTER_CITY), ARRAY_COUNT(sRiftSpots_PEWTER_CITY), sRiftSpots_PEWTER_CITY },
    { MAP_GROUP(MAP_ROUTE3), MAP_NUM(MAP_ROUTE3), ARRAY_COUNT(sRiftSpots_ROUTE3), sRiftSpots_ROUTE3 },
    { MAP_GROUP(MAP_CERULEAN_CITY), MAP_NUM(MAP_CERULEAN_CITY), ARRAY_COUNT(sRiftSpots_CERULEAN_CITY), sRiftSpots_CERULEAN_CITY },
};
