// Generated by scratchpad/anchor_rifts.py -- do not edit by hand.
// Candidate tiles for runtime rift randomisation. Every listed spot is
// walkable, clear of NPCs/warps, and the whole set was verified with all
// spots occupied at once: every warp and map edge still reaches every
// other, so any subset the game picks can never block a route.
//
// The first anchorCount spots of a map sit beside an NPC the rift dropped
// here; the shuffler keeps those fixed and only randomises the rest.

static const struct RiftSpot sRiftSpots_ROUTE1[] = {
    {19, 18}, { 6, 30}, { 8, 24}, {19,  7}, {18, 25}, {13, 35}, { 9, 35}, {15,  9}, {14, 14}, {18, 30}, {18, 14}, { 5, 14}, { 5,  9}, { 6, 19},
};

static const struct RiftSpot sRiftSpots_VIRIDIAN_CITY[] = {
    {34, 28}, {12, 22}, {33, 34}, {22, 35}, {31, 20}, {19, 23}, {20, 28}, {13, 32}, {38, 23}, {39, 28}, {23,  8}, {26, 34}, {37, 34}, {27, 22},
};

static const struct RiftSpot sRiftSpots_ROUTE2[] = {
    { 6,  6}, { 5, 62}, {19, 65}, {11, 61}, {18, 17}, {18, 30}, { 8, 12}, {11, 75}, { 4, 12}, {18, 61}, {19, 75}, {19, 55}, {19, 69}, {18, 36},
};

static const struct RiftSpot sRiftSpots_VIRIDIAN_FOREST[] = {
    { 3, 27}, {13,  9}, {43, 28}, {36, 57}, {15, 59}, {23, 59}, {42, 51}, {46, 60}, {37, 18}, { 8, 58}, {30, 18}, {28, 49}, {41, 39}, {21, 21},
};

static const struct RiftSpot sRiftSpots_PEWTER_CITY[] = {
    {22, 35}, {24, 22}, {17, 33}, {24, 15}, {23, 29}, {32, 29}, {29, 14}, { 8, 27}, {28, 35}, {15, 11}, {33, 22}, {37, 18}, {34,  5}, {10, 12},
};

static const struct RiftSpot sRiftSpots_ROUTE3[] = {
    {75, 15}, {15,  6}, {26, 11}, {59, 14}, {43, 12}, {35, 12}, {70,  6}, {14, 11}, {64, 14}, {70, 15}, {43, 16}, {27,  6}, {39, 15},
};

static const struct RiftSpot sRiftSpots_CERULEAN_CITY[] = {
    {10, 15}, {26, 25}, {37, 19}, {31, 25}, {38, 15}, {35, 25}, { 4, 18}, {12, 22}, {24, 14}, {30, 17}, {19, 23}, {18, 30}, {18,  4},
};

static const struct RiftSpotList sRiftSpotLists[] = {
    { MAP_GROUP(MAP_ROUTE1), MAP_NUM(MAP_ROUTE1), ARRAY_COUNT(sRiftSpots_ROUTE1), 2, sRiftSpots_ROUTE1 },
    { MAP_GROUP(MAP_VIRIDIAN_CITY), MAP_NUM(MAP_VIRIDIAN_CITY), ARRAY_COUNT(sRiftSpots_VIRIDIAN_CITY), 2, sRiftSpots_VIRIDIAN_CITY },
    { MAP_GROUP(MAP_ROUTE2), MAP_NUM(MAP_ROUTE2), ARRAY_COUNT(sRiftSpots_ROUTE2), 0, sRiftSpots_ROUTE2 },
    { MAP_GROUP(MAP_VIRIDIAN_FOREST), MAP_NUM(MAP_VIRIDIAN_FOREST), ARRAY_COUNT(sRiftSpots_VIRIDIAN_FOREST), 4, sRiftSpots_VIRIDIAN_FOREST },
    { MAP_GROUP(MAP_PEWTER_CITY), MAP_NUM(MAP_PEWTER_CITY), ARRAY_COUNT(sRiftSpots_PEWTER_CITY), 0, sRiftSpots_PEWTER_CITY },
    { MAP_GROUP(MAP_ROUTE3), MAP_NUM(MAP_ROUTE3), ARRAY_COUNT(sRiftSpots_ROUTE3), 0, sRiftSpots_ROUTE3 },
    { MAP_GROUP(MAP_CERULEAN_CITY), MAP_NUM(MAP_CERULEAN_CITY), ARRAY_COUNT(sRiftSpots_CERULEAN_CITY), 1, sRiftSpots_CERULEAN_CITY },
};
